swagger: "2.0"

info:
  version: "1.0"
  title: Banka
  description: "Banka is a light-weight core banking application that powers banking operations like account creation, customer deposit and withdrawals. This app is meant to support a single bank, where users can signup and create bank accounts online, but must visit the branch to withdraw or deposit money."
  
host: jbankapp.herokuapp.com
basePath: '/api/v1'

tags: 
  - name : welcome
    description: API for quick api welcome test

  - name : Users
    description: API for users in the app

  - name : Accounts
    description: API for accounts in the app
    
  - name : Transactions
    description: API for Transactions in the app

schemes: 
  - http

consumes:
  - application/json
  - Url encoded

produces:
  - application/json

securityDefinitions :
    basicAuth: 
      type: basic

paths:
  /:
    get: 
      tags: 
        - welcome

      summary : Test get request
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/responce"

  /auth/signup:
    post:
      tags:
        - Users
      summary : Sign up a new user
      parameters:
        - in: body
          name: body
          description: to create a new user
          schema:
            $ref: "#/definitions/usersParam"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/usersSuccessfulResponce"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/responce"

  /auth/signin:
    post:
      tags:
        - Users
      summary : Sign in an existing user
      parameters:
        - in: body
          name: body
          description: to create a new user
          schema:
            $ref: "#/definitions/loginParam"
      responses:
        201:
          description: Created
          schema: 
            $ref: "#/definitions/usersSuccessfulResponce"
        400:
          description: Bad request
          schema: 
            $ref: "#/definitions/responce"

  /accounts:
    post:
      tags:
        - Accounts
      summary : Creates a new user accounts
      security:
        - basicAuth: []
      parameters:
        - in: body
          name: body
          description: to create a new user
          schema:
            $ref: "#/definitions/usersParam"
      responses :
        201:
          description: Created
          schema:
            $ref: "#/definitions/usersSuccessfulResponce"
        400:
          description: Bad request
          schema: 
            $ref: "#/definitions/responce"
  
definitions:
  id:
    type: number

  accounts:
    type: object
    properties:
      accountNumber:
        type: integer
      
      acc:
        type: integer

  usersParam:
    type: object
    properties: 
      firstName: 
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      
  loginParam:
    type: object
    properties:
      email:
        type: string
      password:
        type: string

  usersSuccessfulResponce:
    type: object
    properties: 
      token: 
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string 

  responce:
    type: object
    properties:
      status:
        type: number
      message:
        type: string
